### PR TITLE
Microsoft 365 Defender: Feature - Added HTTP API Timeout as a configurable asset parameter.

### PR DESCRIPTION
**Pull request by ilf0rz**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [X] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Added a timeout parameter in the asset configuration in order to handle situation where microsoft defender 365 APIs take more than 30s to send back response. This avoid getting ReadTimeout errors.

## What is the current behavior? (OPTIONAL)
- If Microsoft Defender 365 API take more than 30s to send back data, actions fail as the timeout is hard-coded in a constant and not configurable.

## What is the new behavior? (OPTIONAL)
- Timeout parameter has been introduced, this will allow to avoid ReadTimeout errors in case API are slow in responding.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)
image

---
Thanks for contributing!

### CODE REVIEW

**Comment by aparekh-crest** [comment]
Hi @ilf0rz ,
I have reviewed your changes and Based on my analysis I observed that the query can be as large as possible to execute from microsoft 365 defender portal, some queries may take more time to run and it depends on the query which is added. 
so my suggestion is that we should remove timeout which is specific to run query action rather than adding configurable timeout, Because it is not sure how exact time will be required to execute the complex queries. 
For instance, action fails by read timeout then the user needs to perform back and forth to identify the actual time to run the query then he will add the value in config parameter or we can remove it so that the failure rate would be reduced.
Please Let me know your thoughts on it.

**Comment by ilf0rz** [comment]
Ciao @aparekh-crest !
You are correct, if the query takes too much time, Microsoft is returning an error due to an expired timeout. We experimented with it, setting a 300s timeout with a very complex query and Microsoft returned an error in the API call. However, removing completely the timeout could lead to cases where connection can potentially hang forever due to a missing default timeout in the requests library. I had to deal with similar situations and drove me and the customer crazy to identify the issue. So I'd rather give the customer the ability to configure the desired timeout, providing a default one in our constants file. Let me know if this makes sense to you.

**Comment by aparekh-crest** [comment]
@ilf0rz I agree, Let's proceed with configurable timeout

**Comment by aparekh-crest** [comment]
Hi @ilf0rz,
I have added your changes to PR: #12, can we close this PR?

**Comment by ilf0rz** [comment]
Sure! Thanks for merging my PR! I hope to see PR#12 will be released soon!

**Comment by aparekh-crest** [comment]
Yes, It will be released within 1-2 months

**Pull request closed without merging**
