### PR TITLE
microsoft 365 defender: bugfix - variable typing issue for encryption/decryption

### PR DESCRIPTION
**Pull request by supergnaw**
For whatever reason, sometimes this function sends an integer instead of a string, which is required in encryption helper. This fixes this issue.

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [x] ~~If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), please document them in the `readme.html`.~~ Not Applicable/No Changes
- [x] ~~If this is a new connector or you are adding new actions~~ Not Applicable/No Changes
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [x] ~~Are you introducing any new cryptography modules? If yes, please elaborate their purpose:~~ Not Applicable/No Changes
- [x] ~~Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.~~ Not Applicable/No Changes
- [x] ~~Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)? If yes, please provide justification in an additional comment next to the ignored code.~~ Not Applicable/No Changes

  

## Release Notes (REQUIRED)
- Fixed typing error where asset ID integer type could cause errors during encryption/decryption of the state file.

## What is the current behavior? (OPTIONAL)
- Sometimes saving/loading the state file will cause a type error due to the asset ID being an integer and not a string.

## What is the new behavior? (OPTIONAL)
- The variable typing is fixed so the error no longer occurs.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by achandya-crest** [comment]
Hello @supergnaw, **Is this issue occurring when the app editor is used?** Because we already have this platform bug reported of this issue being present when anything is run from app editor. 
Analysis ticket: https://splunk.atlassian.net/browse/SOARHELP-1799
Platform bug: https://splunk.atlassian.net/browse/PSAAS-13415

**Comment by achandya-crest** [comment]
Hello @supergnaw, **Is this issue occurring when the app editor is used?** Because we already have this platform bug reported of this issue being present when anything is run from app editor. 
Analysis ticket: https://splunk.atlassian.net/browse/SOARHELP-1799
Platform bug: https://splunk.atlassian.net/browse/PSAAS-13415

**Comment by achandya-crest** [comment]
Hello @supergnaw, Did you get a chance to look into this: https://github.com/splunk-soar-connectors/microsoft365defender/pull/8#issuecomment-1592410058?

**Comment by supergnaw** [comment]
Hello @achandya-crest !

I did look at it and this does appear to be linked to the platform bug, however, since the app does not function as intended, debugging cannot be performed within the app such as refining queries or easily checking action results. As a result, I still believe this pull request to be in the best interest of the app and its userbase.

**Comment by achandya-crest** [comment]
Hello @supergnaw,
This issue of asset_id not being of str type is something that needs to be fixed at a platform level instead of app level because it is used in almost every app of Splunk SOAR. The app correctly fetches the asset_id and uses it as it should and so everything is passing at the container level. But the app editor functionality should be fixed as it manipulates the asset_id fetched.

Hence, we still insist on not making this a code change but a platform change and we request you to use the container action run as it will also help you to see the action_result data and everything that any user would want to check. For debugging, I would suggest you to check the spawn.log and other files on that instance and not make this code change for the same and wait for the platform fix.

**Comment by achandya-crest** [comment]
Thanks for concluding this issue @supergnaw.
According to our discussion(as mentioned in the screenshot below), I am closing this PR.
image

**Pull request closed without merging**
